version: '2'


services:

#########################################################
 #  LOGGING   #
#########################################################
  logstash:
    container_name: logstash
    image: logstash
    expose:
      - 5044
      - 12201/udp
    volumes:
      - ./logstash/conf:/config
    restart: always
    networks:
      default:
        ipv4_address: 192.168.114.27
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.114.27:12201
    command: logstash -f /config --auto-reload

    networks:
      - mynet11
#######################################################
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    ports:
      - 9200:9200
    expose:
      - 9200
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.114.27:12201

    networks:
      - mynet11
#########################################################

  kibana:
    container_name: kibana
    image: kibana
    ports:
      - 5601:5601
    expose:
      - 5601
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.114.27:12201
    environment:
      - NODE_OPTIONS=--max-old-space-size=200

    networks:
      - mynet11
#########################################################
 #  MONITORING #
#########################################################

  nodeexporter:
    container_name: nodeexporter
    image: prom/node-exporter
    expose:
      - 9100
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.114.27:12201

    networks:
      - mynet11
#########################################################

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.114.27:12201

    networks:
      - mynet11
#########################################################

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    volumes:
      - ./prometheus:/etc/prometheus/
    restart: always
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
      - "-alertmanager.url=http://alertmanager:9093"
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.114.27:12201

    networks:
      - mynet11
#########################################################

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.114.27:12201
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - mynet11
#########################################################
#  ALERTING   #
#########################################################

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    expose:
      - 9093
    restart: always
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/simple.yml'
      - '-storage.path=/alertmanager'
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.114.27:12201
    networks:
      - mynet11
#########################################################
#  Networking  #
#########################################################

networks:
   mynet11:
     driver: bridge
######################################################### 
